sonar.organization=kamo-naoyuki
sonar.projectKey=kamo-naoyuki_rotari
sonar.projectName=rotari

sonar.sources=cmd,internal,python/rotari
sonar.tests=cmd,internal,python/tests
sonar.test.inclusions=**/*_test.go,python/tests/**/*.py
sonar.exclusions=docs/**,**/assets/**,**/*.html

sonar.go.coverage.reportPaths=coverage.out
sonar.python.coverage.reportPaths=python-coverage.xml
