package diagnose

import "regexp"

var defaultRules = []Rule{
	{Name: "CUDA/GPU memory exhausted", Patterns: []*regexp.Regexp{regexp.MustCompile(`cuda.*out of memory`), regexp.MustCompile(`\btorch\.cuda\.outofmemoryerror\b`), regexp.MustCompile(`cublas_status_alloc_failed`), regexp.MustCompile(`cudnn_status_alloc_failed`)}, Suggestion: "Reduce batch size or model memory use, select a GPU with more free memory, and check for other processes using the GPU."},
	{Name: "CUDA/GPU unavailable", Patterns: []*regexp.Regexp{regexp.MustCompile(`no cuda-capable device`), regexp.MustCompile(`cuda driver version is insufficient`), regexp.MustCompile(`nvidia-smi has failed`)}, Suggestion: "Confirm that the assigned host has a usable GPU and that the NVIDIA driver and CUDA runtime are compatible."},
	{Name: "Slurm memory limit exceeded", Patterns: []*regexp.Regexp{regexp.MustCompile(`slurmstepd: error: detected .*oom-kill`), regexp.MustCompile(`exceeded job memory limit`), regexp.MustCompile(`state=out_of_memory`)}, Suggestion: "Request more Slurm memory with the appropriate scheduler option or reduce memory use; inspect sacct for the job state and peak memory."},
	{Name: "Slurm time limit exceeded", Patterns: []*regexp.Regexp{regexp.MustCompile(`slurm.*time limit`), regexp.MustCompile(`cancelled .* due to time limit`), regexp.MustCompile(`state=time_limit`)}, Suggestion: "Increase the Slurm time limit if policy permits, or reduce runtime and checkpoint the job before its allocation expires."},
	{Name: "PBS resource or walltime limit exceeded", Patterns: []*regexp.Regexp{regexp.MustCompile(`walltime.*exceeded`), regexp.MustCompile(`exceeded.*walltime`), regexp.MustCompile(`job exceeded.*resource limit`)}, Suggestion: "Increase the requested PBS walltime or resource limit if permitted, or reduce runtime and resource use."},
	{Name: "LSF memory limit exceeded", Patterns: []*regexp.Regexp{regexp.MustCompile(`\bterm_memlimit\b`)}, Suggestion: "Increase the LSF memory limit if permitted, or reduce the job's memory use."},
	{Name: "LSF run time limit exceeded", Patterns: []*regexp.Regexp{regexp.MustCompile(`\bterm_runlimit\b`), regexp.MustCompile(`\bterm_cpulimit\b`)}, Suggestion: "Increase the LSF run or CPU time limit if permitted, or reduce runtime and checkpoint the job."},
	{Name: "Scheduler submission failed", Patterns: []*regexp.Regexp{regexp.MustCompile(`sbatch: error:`), regexp.MustCompile(`qsub:.*error`), regexp.MustCompile(`bsub:.*error`)}, Excludes: []*regexp.Regexp{regexp.MustCompile(`invalid qos specification`), regexp.MustCompile(`invalid partition`), regexp.MustCompile(`invalid account`), regexp.MustCompile(`invalid generic resource`)}, Suggestion: "Check the scheduler command, account or project, partition or queue, requested resources, and submission permissions."},
	{Name: "Invalid scheduler resource request", Patterns: []*regexp.Regexp{regexp.MustCompile(`invalid qos specification`), regexp.MustCompile(`invalid partition`), regexp.MustCompile(`invalid account`), regexp.MustCompile(`invalid generic resource`), regexp.MustCompile(`(?:pbs|lsf).*invalid.*resource`)}, Suggestion: "Check the partition or queue, account, QOS, GPU or resource names, and requested limits."},
	{Name: "Scheduler cancelled job", Patterns: []*regexp.Regexp{regexp.MustCompile(`slurmstepd.*cancelled`), regexp.MustCompile(`state=cancelled`), regexp.MustCompile(`jobstate=cancelled`), regexp.MustCompile(`job.*cancelled by scheduler`), regexp.MustCompile(`pbs.*job.*deleted`), regexp.MustCompile(`\bterm_owner\b`), regexp.MustCompile(`\bterm_admin\b`), regexp.MustCompile(`\bterm_preempt\b`)}, Excludes: []*regexp.Regexp{regexp.MustCompile(`time limit`)}, Suggestion: "Inspect scheduler accounting for the cancellation reason and actor; retry only after resolving policy, preemption, dependency, or administrator cancellation conditions."},
	{Name: "Host memory exhausted", Patterns: []*regexp.Regexp{regexp.MustCompile(`out of memory: kill process`), regexp.MustCompile(`oom-kill`), regexp.MustCompile(`memory cgroup out of memory`), regexp.MustCompile(`killed process .* out of memory`)}, Excludes: []*regexp.Regexp{regexp.MustCompile(`slurmstepd: error: detected .*oom-kill`)}, Suggestion: "Request more host memory or reduce the process memory use; inspect scheduler memory limits and kernel OOM messages."},
	{Name: "Process killed", Patterns: []*regexp.Regexp{regexp.MustCompile(`^killed$`), regexp.MustCompile(`^killed [0-9]+$`)}, Suggestion: "Inspect scheduler accounting and host logs: SIGKILL can result from an OOM killer, a scheduler resource limit, or explicit cancellation."},
	{Name: "Kernel panic or kernel fault", Patterns: []*regexp.Regexp{regexp.MustCompile(`kernel panic`), regexp.MustCompile(`bug: unable to handle kernel`), regexp.MustCompile(`\boops: [0-9a-f]{4}\b`), regexp.MustCompile(`general protection fault`), regexp.MustCompile(`watchdog:.*(?:hard|soft) lockup`), regexp.MustCompile(`rcu.*stall`)}, Suggestion: "Treat the compute node as unhealthy: inspect kernel logs and scheduler node health, report it to the cluster administrator, and retry on another node if appropriate."},
	{Name: "Application panic", Patterns: []*regexp.Regexp{regexp.MustCompile(`^panic:`)}, Suggestion: "Inspect the application stack trace and failing invariant; fix the application error before retrying."},
	{Name: "Segmentation fault", Patterns: []*regexp.Regexp{regexp.MustCompile(`segmentation fault`), regexp.MustCompile(`\bsigsegv\b`), regexp.MustCompile(`\bsignal 11\b`)}, Suggestion: "Inspect native extensions, shared-library and driver compatibility, and a core dump or debugger backtrace if available."},
	{Name: "NVIDIA GPU driver/device error", Patterns: []*regexp.Regexp{regexp.MustCompile(`nvrm: xid`), regexp.MustCompile(`gpu has fallen off the bus`)}, Suggestion: "Inspect GPU and node health plus NVIDIA kernel logs; retry on another GPU or node if appropriate."},
	{Name: "CUDA device-side assert", Patterns: []*regexp.Regexp{regexp.MustCompile(`device-side assert triggered`)}, Suggestion: "Check tensor shapes, labels, and index ranges passed to CUDA kernels; rerun with synchronous CUDA error reporting if needed."},
	{Name: "NCCL failure", Patterns: []*regexp.Regexp{regexp.MustCompile(`\bnccl error`), regexp.MustCompile(`\bnccl warn.*(?:error|fail|abort|timeout|timed out)`), regexp.MustCompile(`nccl.*unhandled system error`)}, Suggestion: "Check GPU and node connectivity, NCCL configuration, network-interface selection, and consistency across distributed ranks."},
	{Name: "MPI runtime failure", Patterns: []*regexp.Regexp{regexp.MustCompile(`\bmpi_abort\b`), regexp.MustCompile(`pmi.*(?:error|failed)`), regexp.MustCompile(`(?:mpirun|mpiexec).*(?:fatal|error|abort)`)}, Suggestion: "Check MPI and runtime compatibility, rank counts, host allocation, and launcher configuration."},
	{Name: "Disk space or quota exhausted", Patterns: []*regexp.Regexp{regexp.MustCompile(`no space left on device`), regexp.MustCompile(`disk quota exceeded`)}, Suggestion: "Free space or files in the relevant filesystem, or use a location with sufficient quota and capacity."},
	{Name: "Storage device I/O error", Patterns: []*regexp.Regexp{regexp.MustCompile(`input/output error`), regexp.MustCompile(`\beio\b`), regexp.MustCompile(`blk_update_request`), regexp.MustCompile(`buffer i/o error`), regexp.MustCompile(`i/o error, dev`)}, Suggestion: "Inspect kernel and storage-service logs, then check the affected disk or network filesystem with the storage administrator before retrying writes."},
	{Name: "Read-only filesystem", Patterns: []*regexp.Regexp{regexp.MustCompile(`read-only file system`), regexp.MustCompile(`\berofs\b`)}, Suggestion: "Check the mount state and write location, then use a writable filesystem."},
	{Name: "File or directory not found", Patterns: []*regexp.Regexp{regexp.MustCompile(`no such file or directory`), regexp.MustCompile(`\bfilenotfounderror\b`), regexp.MustCompile(`\benoent\b`)}, Suggestion: "Check the path, working directory, mounted filesystems, and whether an earlier job produced the required file."},
	{Name: "Permission denied", Patterns: []*regexp.Regexp{regexp.MustCompile(`permission denied`), regexp.MustCompile(`\beacces\b`)}, Excludes: []*regexp.Regexp{regexp.MustCompile(`permission denied \(publickey\)`)}, Suggestion: "Check ownership, file and directory permissions, mount options, and the account used by the job."},
	{Name: "Command or executable not found", Patterns: []*regexp.Regexp{regexp.MustCompile(`command not found`), regexp.MustCompile(`executable file not found`)}, Suggestion: "Check the command spelling and PATH, or use an absolute path and ensure the executable is installed on the execution host."},
	{Name: "Shared library or ABI mismatch", Patterns: []*regexp.Regexp{regexp.MustCompile(`undefined symbol`), regexp.MustCompile(`symbol lookup error`), regexp.MustCompile(`glibcxx_[0-9.]+.*not found`), regexp.MustCompile(`cxxabi_[0-9.]+.*not found`), regexp.MustCompile(`cannot open shared object file`), regexp.MustCompile(`wrong elf class`), regexp.MustCompile(`undefined reference to`)}, Suggestion: "Check ldd output, LD_LIBRARY_PATH, and the loaded .so files; align the compiler, libstdc++, CUDA, and Python-extension ABI versions with the runtime host."},
	{Name: "Python import or module missing", Patterns: []*regexp.Regexp{regexp.MustCompile(`\bmodulenotfounderror\b`), regexp.MustCompile(`\bimporterror\b`), regexp.MustCompile(`cannot import name`)}, Excludes: []*regexp.Regexp{regexp.MustCompile(`undefined symbol`), regexp.MustCompile(`symbol lookup error`), regexp.MustCompile(`glibcxx_[0-9.]+.*not found`), regexp.MustCompile(`cxxabi_[0-9.]+.*not found`), regexp.MustCompile(`cannot open shared object file`), regexp.MustCompile(`wrong elf class`)}, Suggestion: "Check the Python environment, PYTHONPATH, package installation, and version compatibility."},
	{Name: "Python dependency or version conflict", Patterns: []*regexp.Regexp{regexp.MustCompile(`requires .* but .* is installed`), regexp.MustCompile(`dependency resolver`), regexp.MustCompile(`incompatible version`)}, Suggestion: "Check package versions and the environment lockfile or requirements, then install a compatible set."},
	{Name: "Python syntax or indentation error", Patterns: []*regexp.Regexp{regexp.MustCompile(`\bsyntaxerror\b`), regexp.MustCompile(`\bindentationerror\b`), regexp.MustCompile(`\btaberror\b`)}, Suggestion: "Inspect the reported source line for invalid syntax, indentation, tabs, or an incompatible Python language feature."},
	{Name: "Python missing name or attribute", Patterns: []*regexp.Regexp{regexp.MustCompile(`\bnameerror\b`), regexp.MustCompile(`\bunboundlocalerror\b`), regexp.MustCompile(`\battributeerror\b`)}, Suggestion: "Check spelling, imports, object types, and variable initialization along the failing code path."},
	{Name: "Python type or value error", Patterns: []*regexp.Regexp{regexp.MustCompile(`\btypeerror\b`), regexp.MustCompile(`\bvalueerror\b`)}, Suggestion: "Check function arguments, input shapes and formats, and conversions at the reported traceback location."},
	{Name: "Python key or index error", Patterns: []*regexp.Regexp{regexp.MustCompile(`\bkeyerror\b`), regexp.MustCompile(`\bindexerror\b`)}, Suggestion: "Validate dictionary keys, list or array bounds, and assumptions about input or intermediate data."},
	{Name: "Python assertion failed", Patterns: []*regexp.Regexp{regexp.MustCompile(`\bassertionerror\b`)}, Suggestion: "Inspect the failed assertion and the input or invariant it checks; preserve the relevant values in the job log if needed."},
	{Name: "Python memory error", Patterns: []*regexp.Regexp{regexp.MustCompile(`\bmemoryerror\b`)}, Suggestion: "Reduce in-memory data or worker concurrency, stream or batch input, and confirm the scheduler memory limit is sufficient."},
	{Name: "Python recursion limit exceeded", Patterns: []*regexp.Regexp{regexp.MustCompile(`\brecursionerror\b`), regexp.MustCompile(`maximum recursion depth exceeded`)}, Suggestion: "Check for unintended recursion or cycles; rewrite the algorithm iteratively or adjust recursion depth only when safe."},
	{Name: "File descriptor limit exceeded", Patterns: []*regexp.Regexp{regexp.MustCompile(`too many open files`), regexp.MustCompile(`\bemfile\b`)}, Suggestion: "Check file descriptor limits and close leaked descriptors; inspect ulimit -n."},
	{Name: "Process or thread limit exceeded", Patterns: []*regexp.Regexp{regexp.MustCompile(`fork: retry`), regexp.MustCompile(`fork.*resource temporarily unavailable`), regexp.MustCompile(`pthread_create.*resource temporarily unavailable`), regexp.MustCompile(`\beagain\b.*(?:fork|thread|process)`)}, Suggestion: "Check process and thread limits, then reduce worker count or request a suitable scheduler limit."},
	{Name: "DNS lookup failed", Patterns: []*regexp.Regexp{regexp.MustCompile(`temporary failure in name resolution`), regexp.MustCompile(`could not resolve host`), regexp.MustCompile(`no such host`)}, Suggestion: "Check the hostname, DNS resolver configuration, and whether the compute node can reach the configured DNS service."},
	{Name: "Network connection refused", Patterns: []*regexp.Regexp{regexp.MustCompile(`connection refused`), regexp.MustCompile(`\beconnrefused\b`)}, Suggestion: "Check the destination host and port, service availability, and firewall or security-group rules."},
	{Name: "Network connection timed out", Patterns: []*regexp.Regexp{regexp.MustCompile(`connection timed out`), regexp.MustCompile(`i/o timeout`), regexp.MustCompile(`\betimedout\b`)}, Suggestion: "Check network routing, firewall rules, VPN or proxy requirements, and whether the destination is overloaded."},
	{Name: "Network connection reset or closed", Patterns: []*regexp.Regexp{regexp.MustCompile(`connection reset by peer`), regexp.MustCompile(`\beconnreset\b`), regexp.MustCompile(`broken pipe`), regexp.MustCompile(`unexpected eof`)}, Suggestion: "Inspect the remote service for restarts or crashes and check proxy or load-balancer connection timeouts."},
	{Name: "TLS certificate or handshake failure", Patterns: []*regexp.Regexp{regexp.MustCompile(`certificate verify failed`), regexp.MustCompile(`x509: certificate`), regexp.MustCompile(`tls handshake timeout`)}, Suggestion: "Check the system clock, certificate chain and CA configuration, and any TLS-intercepting proxy."},
	{Name: "HTTP authentication or authorization failed", Patterns: append(httpStatusPatterns(`401|403`), regexp.MustCompile(`401 unauthorized`), regexp.MustCompile(`403 forbidden`)), Suggestion: "Check credentials, access tokens, scopes, and the target service's authorization policy."},
	{Name: "HTTP rate limited", Patterns: append(httpStatusPatterns(`429`), regexp.MustCompile(`429 too many requests`), regexp.MustCompile(`rate limit exceeded`)), Suggestion: "Wait or apply exponential backoff, reduce request concurrency, and check the service quota or rate-limit policy."},
	{Name: "HTTP service unavailable", Patterns: append(httpStatusPatterns(`503`), regexp.MustCompile(`503 service unavailable`), regexp.MustCompile(`upstream unavailable`)), Suggestion: "Retry after a delay; if it persists, check service health, maintenance notices, and proxy or load-balancer upstreams."},
	{Name: "HTTP server or bad gateway error", Patterns: append(httpStatusPatterns(`500|502`), regexp.MustCompile(`500 internal server error`), regexp.MustCompile(`502 bad gateway`)), Suggestion: "Retry transient requests and inspect the target service and any proxy or load-balancer logs for the upstream failure."},
	{Name: "HTTP gateway timeout", Patterns: append(httpStatusPatterns(`504`), regexp.MustCompile(`504 gateway timeout`)), Suggestion: "Check target-service latency and proxy timeout settings; retry with backoff when the operation is safe to repeat."},
	{Name: "SSH authentication or host verification failed", Patterns: []*regexp.Regexp{regexp.MustCompile(`permission denied \(publickey\)`), regexp.MustCompile(`host key verification failed`)}, Suggestion: "Check SSH keys and permissions, the known_hosts entry, and SSH server access controls."},
}

// httpStatusPatterns matches HTTP status codes only in an HTTP or status
// context, such as "HTTP/1.1 503", "HTTPError: 503", or "status code 503", so
// that numbers in URLs, file names, or step counters do not match.
func httpStatusPatterns(codes string) []*regexp.Regexp {
	return []*regexp.Regexp{
		regexp.MustCompile(`\bhttp(?:/[0-9.]+)?(?: error)?:? (?:` + codes + `)\b`),
		regexp.MustCompile(`\bhttperror: (?:` + codes + `)\b`),
		regexp.MustCompile(`\bstatus(?:[ _]code)?[:=]? ?(?:` + codes + `)\b`),
		regexp.MustCompile(`\b(?:` + codes + `) (?:client|server) error\b`),
	}
}

func DefaultRules() []Rule {
	return append([]Rule(nil), defaultRules...)
}
