{% set version = environ.get("ROTARI_RELEASE_VERSION", "0.0.0") %}
{% set python_min = "3.10" %}

package:
  name: rotari
  version: {{ version }}

source:
  path: ../..

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - go >=1.22
  host:
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  commands:
    - rotari version
    - rotari --version
    - python -c "import rotari; assert rotari.Rotari"

about:
  home: https://github.com/kamo-naoyuki/rotari
  license: MIT
  license_file: LICENSE
  summary: Manage and run command-line jobs
  dev_url: https://github.com/kamo-naoyuki/rotari

extra:
  recipe-maintainers:
    - kamo-naoyuki
