"""Tests for the LLM documentation output generated by MkDocs."""

from pathlib import Path
import tempfile
import unittest

from mkdocs_llms import _write_outputs


class MkDocsLLMOutputTests(unittest.TestCase):
    def test_writes_index_and_rendered_full_text(self):
        pages = [
            (
                "Getting started",
                "GETTING_STARTED/",
                '<h1>Start</h1><p>See <a href="../FAQ/">FAQ</a>.</p>',
            ),
            (
                "Home",
                "",
                '<h1>rotari documentation</h1><p>Run jobs.</p>'
                '<pre><code class="language-sh">rotari run\n</code></pre>'
                "<script>not documentation</script>",
            ),
        ]

        with tempfile.TemporaryDirectory() as directory:
            site_dir = Path(directory)
            _write_outputs(
                pages,
                site_dir,
                "https://example.test/rotari/docs/",
            )

            index = (site_dir / "llms.txt").read_text(encoding="utf-8")
            full = (site_dir / "llms-full.txt").read_text(encoding="utf-8")

        self.assertLess(index.index("[Home]"), index.index("[Getting started]"))
        self.assertIn(
            "[llms-full.txt](https://example.test/rotari/docs/llms-full.txt)", index
        )
        self.assertIn("Go API site", index)
        self.assertIn("https://example.test/rotari/docs/GETTING_STARTED/", index)
        self.assertIn("Start\nSee FAQ", full)
        self.assertIn("https://example.test/rotari/docs/FAQ/", full)
        self.assertIn("Run jobs.", full)
        self.assertIn("```sh\nrotari run\n```", full)
        self.assertNotIn("not documentation", full)
        self.assertIn("Go API site is not included", full)


if __name__ == "__main__":
    unittest.main()